spring:
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 25MB  #限制文件上传大小为25M
      max-request-size: 25MB  #限制文件上传大小为25M
      location: upload/

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

redis:
  database: item
  key:
    admin: 'blog:ums:admin'
    resourceList: 'blog:ums:resourceList'
  expire:
    common: 86400 # 24小时

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /api/manage/admin/login
      - /api/manage/admin/register
      - /api/manage/admin/info
      - /api/manage/admin/logout
      - /upload/**